language: java
sudo: false
cache: false
jdk:
- openjdk8
env:
  - TMPDIR=/tmp
services:
  - docker
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3
      - python3-dev
      - python3-setuptools
      - unzip
before_install:
- export TZ=Estonia/Tallinn
- python3 --version
- easy_install3 --user future
- easy_install3 --user pyyaml
- easy_install3 --user requests
- easy_install --user pyresttest
branchespython-dev:
  only:
  - develop
install: true
before_script: ls -al $TMPDIR
script: ./mvnw clean install -q -P\!dependency-check
after_success:
- "./mvnw jacoco:report coveralls:report -q -Dcoveralls.repo.token=$COVERALLS_REPO_TOKEN"
notifications:
  email:
    recipients:
    - andres.voll@nortal.com
    - aare.nurm@nortal.com
    - siim.suu@nortal.com
    on_success: change
    on_failure: always
