server:
  port: 9000
  compression:
    enabled: true
  session:
    cookie:
      http-only: false
spring:
  http:
    multipart:
      max-file-size: "10Mb"
  cache:
    caffeine:
      spec: maximumSize=100,expireAfterAccess=20s
management:
  context-path: /monitoring
  health:
    diskspace:
      enabled: false
security:
  basic:
    path: /monitoring/**
  headers:
    cache: false
wro4j:
  filterUrl: /owr
#  cacheName: owr
  managerFactory:
    preProcessors: removeSourceMaps, cssUrlRewriting, cssImport, cssMinJawr, semicolonAppender
endpoints:
  enabled: false
  sensitive: true
  health:
    enabled: true
    sensitive: true